version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - django_static_volume:/usr/src/app/static
    hostname: backend
    expose:
      - 8000
    command: gunicorn QuizManager.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - react_static_volume:/usr/src/app/build/static
    hostname: frontend
    expose:
      - 3000
    command: npm start
    links:
      - backend
    env_file:
      - .env

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile_SSL
    volumes:
      - django_static_volume:/usr/src/app/django_files/static
      - react_static_volume:/usr/src/app/react_files/static
    ports:
      - 8080:8080
      - 443:443
    links:
      - frontend
    env_file:
      - .env

volumes:
  django_static_volume:
  react_static_volume:
