FROM nginx:latest

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx_ssl.conf /etc/nginx/conf.d

COPY nginx-selfsigned.crt /etc/nginx/certs/nginx-selfsigned.crt
COPY nginx-selfsigned.key /etc/nginx/certs/nginx-selfsigned.key
COPY dhparam.pem /etc/nginx/certs/dhparam.pem

WORKDIR /usr/src/app
