name: CI
on: 
  pull_request:
    branches:
      - master 

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created PR to master:            
            Repository: ${{ github.repository }}
            
            Link: https://github.com/${{ github.repository }}/pulls/${{github.event.number}}
